# Generated by Django 4.2.4 on 2023-08-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostgroupmembership',
            name='host',
        ),
        migrations.RemoveField(
            model_name='hostgroupmembership',
            name='host_group',
        ),
        migrations.RemoveField(
            model_name='hostgroupmembershiphistory',
            name='host',
        ),
        migrations.RemoveField(
            model_name='hostgroupmembershiphistory',
            name='host_group',
        ),
        migrations.DeleteModel(
            name='HostGroup',
        ),
        migrations.DeleteModel(
            name='HostGroupMembership',
        ),
        migrations.DeleteModel(
            name='HostGroupMembershipHistory',
        ),
    ]
