# Generated by Django 4.2.4 on 2023-08-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_remove_hostgroupmembership_host_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机'},
        ),
        migrations.AlterModelTable(
            name='host',
            table='ao_host',
        ),
    ]
